# Default values for a k8s template for Digital.ai Release Runner to use in cloud connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "${RUNNER_NAME}"

release:
  registrationToken: "${RUNNER_REGISTRATION_TOKEN}"
  url: "${RELEASE_URL}"

runner:
  activeProfiles: "k8s,json-logging"

image:
  registry:
  repository:
  name: "${AGENT_IMAGE_release-runner}"
  tag:

namespaceOverride: "${DAI_NAMESPACE}"
namespace:
  create: true
  annotations:
    agents.digitalai.cloud/id: "${DAI_AGENT_ID}"

dnsPolicy: Default
hostNetwork: true

resources:
  requests:
    cpu: "${RUNNER_REQUESTS_CPU}"
    memory: "${RUNNER_REQUESTS_MEMORY}"
  limits:
    cpu: "${RUNNER_LIMITS_CPU}"
    memory: "${RUNNER_LIMITS_MEMORY}"
